version: "3.8"

services:
  portfolio:
    build:
      context: ./portfolio-app
    container_name: portfolio
    ports:
      - "8081:80"
    restart: always

  java-container:
    build:
      context: ./java-app
    container_name: java-container
    ports:
      - "8080:8080"
    restart: always
