name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build-test:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4


    # Build Portfolio Docker Image
    - name: Build Portfolio Docker Image
      run: |
        docker build -t portfolio-app ./portfolio-app


    # Build Java Application
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'


    - name: Build Java App with Maven
      run: |
        cd java-app
        mvn clean package -DskipTests


    # Build Java Docker Image
    - name: Build Java Docker Image
      run: |
        docker build -t java-app ./java-app


    # Docker Image Check
    - name: Docker Images
      run: |
        docker images


  deploy:

    needs: build-test

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4


    - name: Deploy using Docker Compose
      run: |
        docker compose up -d


    - name: Show Running Containers
      run: |
        docker ps
